name: bsp
description: Radxa BSP Build Tool
inputs:
  target:
    required: true
  edition:
    required: true
  revision:
    retuired: false
    default: 1
  artifacts:
    required: false
    default: 'false'
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: radxa-repo/bsp
    - name: Install dependency
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install gcc-aarch64-linux-gnu gcc-arm-none-eabi device-tree-compiler u-boot-tools python2-dev
        sudo gem i fpm -f
    - name: Build
      shell: bash
      run: |
        mkdir .output
        pushd .output
        ../bsp -r ${{ inputs.revision }} ${{ inputs.target }} ${{ inputs.edition }}
        popd
    - name: Upload artifacts
      if: inputs.artifacts == 'true' && inputs.board != 'rootfs'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.target }}_${{ inputs.edition }}_${{ inputs.revision }}
        path: .output
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: .output/*
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}